/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GodCard: typeof import('./src/components/GodCard.vue')['default']
    GodCardSkeleton: typeof import('./src/components/GodCardSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_3ab8afbedcfd4631d86cf7f6daa8da7a/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
