blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/mariofdezzz/graphql-network-issues/wiki
    about: Check out the extension documentation
  - name: 💬 Discussions
    url: https://github.com/mariofdezzz/graphql-network-issues/discussions
    about: Join conversations about the project
