name: Build on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create zip from dist
        run: |
          cd dist
          zip -r ../build.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
